/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author Ste
 */
public class AnalogQuizGUI extends javax.swing.JFrame {

    /**
     * Creates new form AnalogQuizGUI
     */
    public AnalogQuizGUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        optionARB = new javax.swing.JRadioButton();
        optionBRB = new javax.swing.JRadioButton();
        optionCRB = new javax.swing.JRadioButton();
        submitBtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        headingLbl = new javax.swing.JLabel();
        QuestionLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Arial Hebrew", 1, 14)); // NOI18N
        Title.setForeground(new java.awt.Color(0, 102, 255));
        Title.setText("Chose one of the following anwsers:");
        getContentPane().add(Title);
        Title.setBounds(0, 240, 277, 16);

        optionARB.setText("increase transformer");
        optionARB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionARBActionPerformed(evt);
            }
        });
        getContentPane().add(optionARB);
        optionARB.setBounds(120, 320, 162, 23);

        optionBRB.setBackground(new java.awt.Color(255, 255, 255));
        optionBRB.setText("Step-up transformer");
        getContentPane().add(optionBRB);
        optionBRB.setBounds(120, 360, 290, 23);

        optionCRB.setText("Step-down transformer");
        getContentPane().add(optionCRB);
        optionCRB.setBounds(120, 280, 179, 23);

        submitBtn.setBackground(new java.awt.Color(0, 102, 255));
        submitBtn.setText("Submit ");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(submitBtn);
        submitBtn.setBounds(50, 410, 280, 40);

        exitbtn .setOpaque(false);
        exitbtn .setContentAreaFilled(false);
        exitbtn .setBorderPainted(false);
        exitbtn.setBackground(new java.awt.Color(249, 244, 244));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn);
        exitbtn.setBounds(0, 0, 90, 50);

        headingLbl.setFont(new java.awt.Font("Arial Hebrew", 1, 15)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(0, 102, 255));
        headingLbl.setText("Question:");
        getContentPane().add(headingLbl);
        headingLbl.setBounds(0, 160, 76, 16);

        QuestionLbl.setText("What type of transformer is used to increase voltage ?");
        getContentPane().add(QuestionLbl);
        QuestionLbl.setBounds(5, 156, 390, 70);

        jLabel3.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Analog Quiz");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 10, 220, 39);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/QuizGUI3.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitBtnActionPerformed

    private void optionARBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionARBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_optionARBActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalogQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalogQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalogQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalogQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalogQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JLabel Title;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton optionARB;
    private javax.swing.JRadioButton optionBRB;
    private javax.swing.JRadioButton optionCRB;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
