/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;

/**
 *
 * @author Stephen
 */
public class AnalogResistorCalcPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResistorCalcPanel
     */
    public AnalogResistorCalcPanel() {
        initComponents();
        this.setSize(550,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        frstnumLbl = new javax.swing.JLabel();
        secondcolorLbl = new javax.swing.JLabel();
        thridcolorLbl = new javax.swing.JLabel();
        toloeranceLbl = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        anwserLbl = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        headingLbl = new javax.swing.JLabel();
        Color1CB = new javax.swing.JComboBox();
        Color2CB = new javax.swing.JComboBox();
        Color3CB = new javax.swing.JComboBox();
        ToloeranceCB = new javax.swing.JComboBox();
        TitleLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(null);

        frstnumLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        frstnumLbl.setForeground(new java.awt.Color(255, 255, 255));
        frstnumLbl.setText("First color:");
        add(frstnumLbl);
        frstnumLbl.setBounds(20, 270, 90, 20);

        secondcolorLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        secondcolorLbl.setForeground(new java.awt.Color(255, 255, 255));
        secondcolorLbl.setText("Second color:");
        add(secondcolorLbl);
        secondcolorLbl.setBounds(140, 260, 90, 30);

        thridcolorLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        thridcolorLbl.setForeground(new java.awt.Color(255, 255, 255));
        thridcolorLbl.setText("Third color:");
        add(thridcolorLbl);
        thridcolorLbl.setBounds(280, 260, 90, 30);

        toloeranceLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        toloeranceLbl.setForeground(new java.awt.Color(255, 255, 255));
        toloeranceLbl.setText("Toloerance:");
        add(toloeranceLbl);
        toloeranceLbl.setBounds(430, 260, 80, 30);

        addBtn.setText("Calculate");
        add(addBtn);
        addBtn.setBounds(20, 410, 180, 30);

        anwserLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        anwserLbl.setForeground(new java.awt.Color(255, 255, 255));
        anwserLbl.setText(" = 365ohm");
        add(anwserLbl);
        anwserLbl.setBounds(120, 360, 270, 40);

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        add(ResetBtn);
        ResetBtn.setBounds(350, 410, 170, 30);

        headingLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(255, 255, 255));
        headingLbl.setText("Resistor Value:");
        add(headingLbl);
        headingLbl.setBounds(10, 320, 130, 30);

        Color1CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(Color1CB);
        Color1CB.setBounds(10, 290, 101, 27);

        Color2CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(Color2CB);
        Color2CB.setBounds(140, 290, 101, 27);

        Color3CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Orange", "Yellow", "Green", "Blue", "Violet", "Grey", "White" }));
        add(Color3CB);
        Color3CB.setBounds(270, 290, 101, 27);

        ToloeranceCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Brown", "Red", "Green", "Blue", "Violet", "Grey", "Gold", "Silver", "None" }));
        add(ToloeranceCB);
        ToloeranceCB.setBounds(420, 290, 94, 27);

        TitleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Resistor value calculator ");
        add(TitleLbl);
        TitleLbl.setBounds(160, 0, 340, 30);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(-3, -10, 100, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/CalcGUI.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 550, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        AnalogResistorCalcPanel reset = new AnalogResistorCalcPanel();
        anwserLbl.setText("");
        
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Color1CB;
    private javax.swing.JComboBox Color2CB;
    private javax.swing.JComboBox Color3CB;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JComboBox ToloeranceCB;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel frstnumLbl;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel secondcolorLbl;
    private javax.swing.JLabel thridcolorLbl;
    private javax.swing.JLabel toloeranceLbl;
    // End of variables declaration//GEN-END:variables
}
