/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import javax.swing.JPanel;

/**
 *
 * @author Stephen kearns
 */
public class AnalogGUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalogGUI
     */
 
    public AnalogGUIPanel() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HangmanBtn = new javax.swing.JButton();
        QuizBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();
        DiagnosticBtn = new javax.swing.JButton();
        CalcBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        HangmanBtn.setText("Hangman");
        add(HangmanBtn);
        HangmanBtn.setBounds(40, 20, 190, 29);

        QuizBtn.setText("Quiz");
        QuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBtnActionPerformed(evt);
            }
        });
        add(QuizBtn);
        QuizBtn.setBounds(100, 100, 170, 29);

        InfoBtn.setText("Information");
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });
        add(InfoBtn);
        InfoBtn.setBounds(160, 190, 150, 29);

        DiagnosticBtn.setText("Diagnostic Tool");
        add(DiagnosticBtn);
        DiagnosticBtn.setBounds(130, 290, 160, 29);

        CalcBtn.setText("Resistor calculate ");
        add(CalcBtn);
        CalcBtn.setBounds(40, 380, 180, 29);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/AnalogGUI.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 410, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void QuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogQuizScreen");
        }
    }//GEN-LAST:event_QuizBtnActionPerformed

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogInfoScreen");
        }
    }//GEN-LAST:event_InfoBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcBtn;
    private javax.swing.JButton DiagnosticBtn;
    private javax.swing.JButton HangmanBtn;
    private javax.swing.JButton InfoBtn;
    private javax.swing.JButton QuizBtn;
    private javax.swing.JLabel backgroundLbl;
    // End of variables declaration//GEN-END:variables
}
