/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.CardLayout;
import java.awt.FlowLayout;
import javax.swing.JPanel;

/**
 *
 * @author Stephen kearns
 */
public class AnalogGUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalogGUI
     */
    JPanel cardsContainer;
    public AnalogGUIPanel() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("Hangman");
        add(jButton1);
        jButton1.setBounds(20, 20, 190, 29);

        jButton2.setText("Quiz");
        add(jButton2);
        jButton2.setBounds(100, 100, 170, 29);

        jButton3.setText("Information");
        add(jButton3);
        jButton3.setBounds(160, 190, 150, 29);

        jButton4.setText("Diagnostic Tool");
        add(jButton4);
        jButton4.setBounds(130, 290, 160, 29);

        jButton5.setText("Resistor calculate ");
        add(jButton5);
        jButton5.setBounds(40, 380, 180, 29);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/AnalogGUI.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 410, 430);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
