/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author Sean
 */
public class DiganosticGUI extends javax.swing.JFrame {

    /**
     * Creates new form DiganosticGUI
     */
    public DiganosticGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        anwserLbl = new javax.swing.JLabel();
        infoLbl = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        nameLbl.setBackground(new java.awt.Color(0, 102, 255));
        nameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 102, 255));
        nameLbl.setText("Name:");
        getContentPane().add(nameLbl);
        nameLbl.setBounds(10, 260, 50, 30);

        descriptionLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        descriptionLbl.setForeground(new java.awt.Color(0, 102, 255));
        descriptionLbl.setText("Use:");
        getContentPane().add(descriptionLbl);
        descriptionLbl.setBounds(10, 310, 90, 17);

        anwserLbl.setText("oscilloscope");
        getContentPane().add(anwserLbl);
        anwserLbl.setBounds(70, 266, 140, 20);

        infoLbl.setText("To observe the change of an electrical signal over time.");
        getContentPane().add(infoLbl);
        infoLbl.setBounds(10, 340, 410, 50);

        exitBtn.setBackground(new java.awt.Color(0, 102, 255));
        exitBtn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        exitBtn.setText("Exit");
        getContentPane().add(exitBtn);
        exitBtn.setBounds(280, 410, 110, 40);

        nextBtn  .setOpaque(false);
        nextBtn  .setContentAreaFilled(false);
        nextBtn  .setBorderPainted(false);
        getContentPane().add(nextBtn);
        nextBtn.setBounds(310, 0, 75, 40);

        backBtn .setOpaque(false);
        backBtn .setContentAreaFilled(false);
        backBtn .setBorderPainted(false);
        getContentPane().add(backBtn);
        backBtn.setBounds(0, 0, 75, 40);

        jLabel2.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        jLabel2.setText("Diagnostic tools");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 10, 190, 30);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/DiganosticGUI.png"))); // NOI18N
        backgroundLbl.setText("jLabel1");
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiganosticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiganosticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiganosticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiganosticGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiganosticGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel infoLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton nextBtn;
    // End of variables declaration//GEN-END:variables
}
