/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author Stephen
 */
public class DiganosticGUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form DiganosticGUIPanel
     */
    public DiganosticGUIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        anwserLbl = new javax.swing.JLabel();
        useLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        titleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        titleLbl.setText("Analog Section");
        add(titleLbl);
        titleLbl.setBounds(140, 0, 160, 40);

        nameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(0, 102, 255));
        nameLbl.setText("Name:");
        add(nameLbl);
        nameLbl.setBounds(10, 256, 70, 30);

        anwserLbl.setText("Oscilloscope");
        add(anwserLbl);
        anwserLbl.setBounds(70, 264, 240, 16);

        useLbl.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        useLbl.setForeground(new java.awt.Color(0, 102, 255));
        useLbl.setText("Use:");
        add(useLbl);
        useLbl.setBounds(10, 310, 70, 20);

        jLabel2.setText("To observe the change of an electrical signal over time.");
        add(jLabel2);
        jLabel2.setBounds(20, 330, 370, 70);

        exitBtn.setBackground(new java.awt.Color(0, 102, 255));
        exitBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        exitBtn.setText("Exit");
        add(exitBtn);
        exitBtn.setBounds(225, 399, 150, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/DiganosticGUI.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel useLbl;
    // End of variables declaration//GEN-END:variables
}
