/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Stephen 
 */
public class DigitalQuizScreen extends javax.swing.JPanel {
    protected String answer, question, userAns, sentance; 
    protected String[] userAnswer;
    private static String[] randomizedQuestion;
    protected int correct, incorrect;
    private boolean chckRightorWrong;
    public QuestionObj obj;
    public static ArrayList <QuestionObj> objArr;
        
    /**
     * Creates new form QuizGUIPanel
     */
    public DigitalQuizScreen() {
        initComponents();
        this.setSize(400,450);
        obj = new QuestionObj();
        objArr = new ArrayList<>();
        randomizedQuestion = new String[10];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param objArr
     */
    public void setarr(String[] randomizedQuestion){
     this.randomizedQuestion = randomizedQuestion;
    }
    public void setobjarr(ArrayList<QuestionObj> objArr){
        DigitalQuizScreen.objArr = objArr;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        headingLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headingLbl.setForeground(new java.awt.Color(255, 255, 255));
        headingLbl.setText("Question:");
        add(headingLbl);
        headingLbl.setBounds(10, 120, 100, 17);

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setText("What device is used to test voltage in a circuit");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(10, 140, 380, 60);

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Multimeter");
        add(jRadioButton1);
        jRadioButton1.setBounds(140, 240, 170, 23);

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("Logic probe");
        add(jRadioButton2);
        jRadioButton2.setBounds(140, 290, 180, 23);

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("Soldering Iron");
        add(jRadioButton3);
        jRadioButton3.setBounds(140, 340, 180, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chose one of the following anwser's:");
        add(jLabel1);
        jLabel1.setBounds(20, 210, 270, 17);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(200, 400, 150, 40);

        titleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Digital Quiz");
        add(titleLbl);
        titleLbl.setBounds(140, 0, 200, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setText("return to menu");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(20, 400, 150, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/FEATURE-BRAIN-CIRCUITS-ISTOCK-HiRes.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(4, 4, 390, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "DigitalSectionScreen");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         Quiz playQuiz = new Quiz();
         //objArr = playQuiz.getarrlist();
        //String[] temp = playQuiz.choseRandomQuestion();
        userAnswer = new String[10];
       for(int i = 0; i < 10; i++){
           int counter = 0;
           //JOptionPane.showMessageDialog(null,objArr.get(0).getquestion()+ objArr.get(1).getquestion());
           String temp = objArr.get(i).getquestion();
           JOptionPane.showMessageDialog(null, counter);
           answer = JOptionPane.showInputDialog(temp);
           do{
           /*
           if(jRadioButton1.isSelected()){
           answer = "a";
           counter = 1;
           }
           else if(jRadioButton.isSelected()){
           answer = "b";
            counter = 1;
           }
           else if(jRadioButton.isSelected()){
           answer = "c";
           counter = 1;
           }
           */
                if(answer == null || answer.equals("") || answer.equals(" ")){
                    answer = JOptionPane.showInputDialog("please enter a valid answer: " + temp);
                    counter = 0;
                 }
                else{
                counter = 1;
                }
           }while(counter == 0);
           userAnswer[i] = answer;
       }
       
       playQuiz.setAnswer(userAnswer);
       playQuiz.setobj(objArr);
       playQuiz.checkAnwsers();
       correct = playQuiz.getcorrect();
       incorrect = playQuiz.getIncorrect();
       JOptionPane.showMessageDialog(null,"The number of correct anwsers is:" + " "+correct + " " + "The number of incorrect question is:" + " "+ incorrect);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
