/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author magui_000
 */
public class PlasticCatagoriesGUI extends javax.swing.JPanel {

    /**
     * Creates new form PlasticCatagoriesGUI
     */
    public PlasticCatagoriesGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NextBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        TitleLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        NextBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NextBtn.setText("Next");
        add(NextBtn);
        NextBtn.setBounds(60, 370, 130, 30);

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn);
        ExitBtn.setBounds(220, 370, 130, 30);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Catagory Name");
        add(TitleLbl);
        TitleLbl.setBounds(120, 30, 200, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/newseventsimages.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton NextBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
