/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager; 

/**
 *
 * @author magui_000
 */
public class PlasticInfoGUI extends javax.swing.JPanel {

    /**
     * Creates new form PlasticInfoGUI
     */
    public PlasticInfoGUI() {
        initComponents();
        this.setSize(400,450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExitBtn = new javax.swing.JButton();
        InfoLbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        PictureLbl = new javax.swing.JLabel();
        BackgroungLbl = new javax.swing.JLabel();

        setLayout(null);

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn);
        ExitBtn.setBounds(230, 370, 120, 40);

        InfoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/plastic info.PNG"))); // NOI18N
        add(InfoLbl);
        InfoLbl.setBounds(30, 274, 340, 40);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setText("Information");
        add(TitleLbl);
        TitleLbl.setBounds(140, 10, 110, 22);

        PictureLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/Plastics_Industry_in_the_Middle_East.jpg"))); // NOI18N
        PictureLbl.setText("jLabel1");
        add(PictureLbl);
        PictureLbl.setBounds(50, 50, 290, 200);

        BackgroungLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/InformationGUI.png"))); // NOI18N
        BackgroungLbl.setText("jLabel2");
        add(BackgroungLbl);
        BackgroungLbl.setBounds(0, 0, 400, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
         LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "PlasticMainScreen");
    }//GEN-LAST:event_ExitBtnActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlasticMainGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroungLbl;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JLabel InfoLbl;
    private javax.swing.JLabel PictureLbl;
    private javax.swing.JLabel TitleLbl;
    // End of variables declaration//GEN-END:variables
}
