/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author magui_000
 */
public class PlasticInfoGUI extends javax.swing.JPanel {

    /**
     * Creates new form PlasticInfoGUI
     */
    public PlasticInfoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        CatagoriesBtn = new javax.swing.JButton();
        ExamplesBtn = new javax.swing.JButton();
        WhatMadeBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        BackBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BackBtn.setText("Back to Materials");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn);
        BackBtn.setBounds(120, 283, 150, 30);

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        add(ExitBtn);
        ExitBtn.setBounds(110, 330, 150, 30);

        CatagoriesBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CatagoriesBtn.setText("Catagories");
        CatagoriesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatagoriesBtnActionPerformed(evt);
            }
        });
        add(CatagoriesBtn);
        CatagoriesBtn.setBounds(110, 110, 150, 30);

        ExamplesBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ExamplesBtn.setText("Examples");
        ExamplesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamplesBtnActionPerformed(evt);
            }
        });
        add(ExamplesBtn);
        ExamplesBtn.setBounds(120, 160, 150, 30);

        WhatMadeBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WhatMadeBtn.setText("What is it Made of");
        WhatMadeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhatMadeBtnActionPerformed(evt);
            }
        });
        add(WhatMadeBtn);
        WhatMadeBtn.setBounds(120, 210, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/OOP Picture.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 440);
    }// </editor-fold>//GEN-END:initComponents

    private void CatagoriesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatagoriesBtnActionPerformed
        // TODO add your handling code here:
        PlasticCatagoriesGUI myPCat = new PlasticCatagoriesGUI();
        myPCat.setVisible(true);
    }//GEN-LAST:event_CatagoriesBtnActionPerformed

    private void ExamplesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamplesBtnActionPerformed
        // TODO add your handling code here:
        PlasticExampleGUI myPExample = new PlasticExampleGUI();
        myPExample.setVisible(true);
    }//GEN-LAST:event_ExamplesBtnActionPerformed

    private void WhatMadeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhatMadeBtnActionPerformed
        // TODO add your handling code here:
        PlasticMadeOfGUI myPMade = new PlasticMadeOfGUI();
        myPMade.setVisible(true);
    }//GEN-LAST:event_WhatMadeBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlasticMainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlasticMainGUI().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton CatagoriesBtn;
    private javax.swing.JButton ExamplesBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton WhatMadeBtn;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
