/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author magui_000
 */
public class PlasticQuizGUI extends javax.swing.JPanel {

    /**
     * Creates new form PlasticQuizGUI
     */
    public PlasticQuizGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLbl = new javax.swing.JLabel();
        Ans1RBtn = new javax.swing.JRadioButton();
        Ans2RBtn = new javax.swing.JRadioButton();
        Ans3RBtn = new javax.swing.JRadioButton();
        Ans4RBtn = new javax.swing.JRadioButton();
        SubmitBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("Quiz");
        add(TitleLbl);
        TitleLbl.setBounds(160, 30, 40, 22);

        Ans1RBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ans1RBtn.setText("Answer 1");
        add(Ans1RBtn);
        Ans1RBtn.setBounds(50, 210, 90, 25);

        Ans2RBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ans2RBtn.setText("Answer 2");
        add(Ans2RBtn);
        Ans2RBtn.setBounds(50, 280, 90, 25);

        Ans3RBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ans3RBtn.setText("Answer 3");
        add(Ans3RBtn);
        Ans3RBtn.setBounds(230, 210, 93, 23);

        Ans4RBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ans4RBtn.setText("Answer 4");
        add(Ans4RBtn);
        Ans4RBtn.setBounds(230, 280, 90, 25);

        SubmitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        SubmitBtn.setText("Submit");
        add(SubmitBtn);
        SubmitBtn.setBounds(50, 370, 100, 29);

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ExitBtn.setText("Exit");
        add(ExitBtn);
        ExitBtn.setBounds(220, 370, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/newseventsimages.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 440);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ans1RBtn;
    private javax.swing.JRadioButton Ans2RBtn;
    private javax.swing.JRadioButton Ans3RBtn;
    private javax.swing.JRadioButton Ans4RBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
