/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hassan
 */
public class QuizScreen extends javax.swing.JPanel {
     protected String answer, question, userAns, sentance, name; 
    protected String[] userAnswer;
    private static String[] randomizedQuestion;
    protected int correct, incorrect;
    private boolean chckRightorWrong;
    public QuestionObj obj;
    public static ArrayList <QuestionObj> objArr;
    int counter , random;
    int btntrack;
    protected Random rand;
    String gamemode;
    String message;
    int CompPlays;
    AILogic myAILogic = new AILogic();
    
        
    /**
     * Creates new form QuizGUIPanel
     */
    public QuizScreen() {
        initComponents();
        this.setSize(400,450);
         obj = new QuestionObj();
        objArr = new ArrayList<>();
        
        randomizedQuestion = new String[10];
        counter = 0;
        userAnswer = new String[10];
        btntrack = 0;
        random = 0;
        rand = new Random();
        CompPlays = 1;
        message = "";
       jButton1.setVisible(false);
        Savebtn.setVisible(false);
        Nametf.setVisible(false);
    }
    
     public void setobjarr(ArrayList<QuestionObj> objArr){
        QuizScreen.objArr = objArr;
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headingLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Savebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        scorebtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        Nametf = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        levelCB = new javax.swing.JComboBox();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        headingLbl.setText("Question:");
        add(headingLbl);
        headingLbl.setBounds(10, 120, 80, 14);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        add(jLabel3);
        jLabel3.setBounds(10, 150, 370, 20);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        add(jLabel2);
        jLabel2.setBounds(10, 164, 370, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1);
        jRadioButton1.setBounds(110, 240, 210, 21);

        buttonGroup1.add(jRadioButton2);
        add(jRadioButton2);
        jRadioButton2.setBounds(110, 290, 210, 21);

        buttonGroup1.add(jRadioButton3);
        add(jRadioButton3);
        jRadioButton3.setBounds(110, 340, 210, 21);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Chose one of the following anwser's then press next to submit:");
        add(jLabel1);
        jLabel1.setBounds(10, 210, 380, 14);

        jButton2.setText("Start");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(20, 390, 150, 40);

        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        add(Savebtn);
        Savebtn.setBounds(110, 390, 150, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(110, 390, 150, 40);

        scorebtn.setText("View previous score");
        scorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorebtnActionPerformed(evt);
            }
        });
        add(scorebtn);
        scorebtn.setBounds(220, 390, 150, 40);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(0, 0, 70, 40);

        Nametf.setText("Enter name here");
        add(Nametf);
        Nametf.setBounds(110, 260, 210, 30);

        titleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Test you knowledge");
        add(titleLbl);
        titleLbl.setBounds(90, 0, 200, 40);

        levelCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Easy", "Medium", "Hard" }));
        add(levelCB);
        levelCB.setBounds(290, -3, 110, 50);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/QuizGUI3.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Quiz playQuiz = new Quiz();
           int i =0;
         //objArr = playQuiz.getarrlist();
        //String[] temp = playQuiz.choseRandomQuestion();
        
        
           //JOptionPane.showMessageDialog(null,objArr.get(0).getquestion()+ objArr.get(1).getquestion());
           if(counter < 10){
            random = rand.nextInt(3);
               
            if(jRadioButton1.isSelected()){
           userAnswer[counter] = "a";
          
           }
           else if(jRadioButton2.isSelected()){
           userAnswer[counter] = "b";
            
           }
           else if(jRadioButton3.isSelected()){
           userAnswer[counter] = "c";
           }
            else{
                   jLabel3.setText("please select a radio buttion " + objArr.get(counter).getquestion());
                    counter = -1;
                 }
           
           if(counter < 9){
           jLabel3.setText(objArr.get(counter + 1).getquestion());
        if(objArr.get(counter + 1).getrad().equals("a")){
        jRadioButton1.setText(objArr.get(counter + 1).getanswer());
        jRadioButton2.setText(objArr.get(counter + 1).getincorrect1());
        jRadioButton3.setText(objArr.get(counter + 1).getincorrect2());
        }
        else if(objArr.get(counter + 1).getrad().equals("b")){
        jRadioButton2.setText(objArr.get(counter + 1).getanswer());
        jRadioButton1.setText(objArr.get(counter + 1).getincorrect1());
        jRadioButton3.setText(objArr.get(counter + 1).getincorrect2());
        }
        else if(objArr.get(counter + 1).getrad().equals("c")){
         jRadioButton3.setText(objArr.get(counter + 1).getanswer());
        jRadioButton2.setText(objArr.get(counter + 1).getincorrect1());
        jRadioButton1.setText(objArr.get(counter + 1).getincorrect2());
        }
        else{
        JOptionPane.showMessageDialog(null, "something has gone wrong one of the devlopers has assigned the answer to an invalid value");
        }
           }
            if(counter == 9){
           jButton1.setText("get results");
            
             
           }
           counter++;
          
           }
           else{
       playQuiz.setAnswer(userAnswer);
       playQuiz.setobj(objArr);
       playQuiz.checkAnwsers();
       correct = playQuiz.getcorrect();
       incorrect = playQuiz.getIncorrect();
       message = myAILogic.getMessage();
      
       jLabel3.setText("The number of correct anwsers is:" + " "+correct );
       jLabel2.setText("The number of incorrect question is:" + " "+ incorrect);
        JOptionPane.showMessageDialog(null,message);
       jRadioButton3.setVisible(false);
        jRadioButton2.setVisible(false);
        jRadioButton1.setVisible(false);
        Nametf.setVisible(true);
        Savebtn.setVisible(true);
        jLabel1.setText("To save your score please enter your name and press save");
       //JOptionPane.showMessageDialog(null,"The number of correct anwsers is:" + " "+correct + " " + "The number of incorrect question is:" + " "+ incorrect);
           
        
        
           }
            if(CompPlays == 1){
            gamemode = levelCB.getSelectedItem().toString().toLowerCase();
            myAILogic.setGamemode(gamemode);
            myAILogic.calRight();
            myAILogic.whatQuestions();
            CompPlays ++;
           }
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         jButton2.setVisible(false);
         scorebtn.setVisible(false);
         jButton1.setVisible(true);
        jLabel3.setText(objArr.get(counter).getquestion());
        if(objArr.get(counter).getrad().equals("a")){
        jRadioButton1.setText(objArr.get(counter).getanswer());
        jRadioButton2.setText(objArr.get(counter).getincorrect1());
        jRadioButton3.setText(objArr.get(counter).getincorrect2());
        }
        else if(objArr.get(counter).getrad().equals("b")){
        jRadioButton2.setText(objArr.get(counter).getanswer());
        jRadioButton1.setText(objArr.get(counter).getincorrect1());
        jRadioButton3.setText(objArr.get(counter).getincorrect2());
        }
        else if(objArr.get(counter).getrad().equals("c")){
         jRadioButton3.setText(objArr.get(counter).getanswer());
        jRadioButton2.setText(objArr.get(counter).getincorrect1());
        jRadioButton1.setText(objArr.get(counter).getincorrect2());
        }
        else{
        JOptionPane.showMessageDialog(null, "something has gone wrong one of the devlopers has assigned the answer to an invalid value");
        }
        
        
            
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void difficultyCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_difficultyCBActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        name = Nametf.getText();
        UserScoreObj save = new UserScoreObj();
        save.setName(name);
        save.setIncorrect(incorrect);
        save.setcorrect(correct);
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        try{
        outFile = new File("userScore.data");
        fStream = new FileOutputStream(outFile);
        oStream = new ObjectOutputStream(fStream);
        
        oStream.writeObject(save);
        JOptionPane.showMessageDialog(null,"your score has been saved");
        oStream.close();
        
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void scorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorebtnActionPerformed
        // TODO add your handling code here:
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
        inFile = new File("userScore.data");
        fStream = new FileInputStream(inFile);
        oStream = new ObjectInputStream(fStream);
        UserScoreObj readPrev;
        
        readPrev = (UserScoreObj)oStream.readObject();
        
        JOptionPane.showMessageDialog(null, "Name:" + readPrev.getName() + "Correct answers: " + readPrev.getCorrect() + "Incorrect answers: " + readPrev.getIncorrect());
        oStream.close();
        }
        catch(IOException e){
        JOptionPane.showMessageDialog(null, e + "cannot find save file");
        } catch (ClassNotFoundException ex) {
             Logger.getLogger(QuizScreen.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, ex + "cannot find class");
         }
    }//GEN-LAST:event_scorebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nametf;
    private javax.swing.JButton Savebtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JComboBox levelCB;
    private javax.swing.JButton scorebtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
