/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

import java.awt.LayoutManager;

/**
 *
 * @author Stephen 
 */
public class QuizGUIPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuizGUIPanel
     */
    public QuizGUIPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLbl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();

        setLayout(null);

        headingLbl.setText("Question:");
        add(headingLbl);
        headingLbl.setBounds(10, 120, 80, 16);

        jTextField1.setText("What type of transformer is used to increase voltage ?");
        add(jTextField1);
        jTextField1.setBounds(10, 140, 380, 60);

        jRadioButton1.setText("increase transformer");
        add(jRadioButton1);
        jRadioButton1.setBounds(140, 240, 170, 23);

        jRadioButton2.setText("Step-up transformer");
        add(jRadioButton2);
        jRadioButton2.setBounds(140, 290, 180, 23);

        jRadioButton3.setText("Step-down transformer");
        add(jRadioButton3);
        jRadioButton3.setBounds(140, 340, 180, 23);

        jLabel1.setText("Chose one of the following anwser's:");
        add(jLabel1);
        jLabel1.setBounds(20, 210, 240, 16);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setText("Submit");
        add(jButton1);
        jButton1.setBounds(110, 390, 150, 40);

        exitBtn .setOpaque(false);
        exitBtn .setContentAreaFilled(false);
        exitBtn .setBorderPainted(false);
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        add(exitBtn);
        exitBtn.setBounds(0, 0, 75, 40);

        titleLbl.setFont(new java.awt.Font("Apple Chancery", 1, 18)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("Analog Quiz");
        add(titleLbl);
        titleLbl.setBounds(140, 0, 200, 40);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analogsection/QuizGUI3.png"))); // NOI18N
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 400, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "AnalogMainScreen");
        }
    }//GEN-LAST:event_exitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
