/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;

/**
 *
 * @author Sean
 */
public class ResistorCalcPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResistorCalcPanel
     */
    public ResistorCalcPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        frstnumLbl = new javax.swing.JLabel();
        secondcolorLbl = new javax.swing.JLabel();
        thridcolorLbl = new javax.swing.JLabel();
        toloeranceLbl = new javax.swing.JLabel();
        firstcolorLbl = new javax.swing.JTextField();
        secondcolorTf = new javax.swing.JTextField();
        thirdcolorLbl = new javax.swing.JTextField();
        toloeranceTf = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        anwserLbl = new javax.swing.JLabel();
        ResetBtn = new javax.swing.JButton();
        headingLbl = new javax.swing.JLabel();
        backgroundLbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setLayout(null);

        frstnumLbl.setText("First color:");
        add(frstnumLbl);
        frstnumLbl.setBounds(10, 180, 90, 20);

        secondcolorLbl.setText("Second color:");
        add(secondcolorLbl);
        secondcolorLbl.setBounds(130, 170, 90, 30);

        thridcolorLbl.setText("Third color:");
        add(thridcolorLbl);
        thridcolorLbl.setBounds(260, 170, 90, 30);

        toloeranceLbl.setText("Toloerance:");
        add(toloeranceLbl);
        toloeranceLbl.setBounds(400, 170, 80, 30);

        firstcolorLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstcolorLblActionPerformed(evt);
            }
        });
        add(firstcolorLbl);
        firstcolorLbl.setBounds(0, 200, 100, 28);
        add(secondcolorTf);
        secondcolorTf.setBounds(120, 200, 110, 28);
        add(thirdcolorLbl);
        thirdcolorLbl.setBounds(250, 200, 110, 28);
        add(toloeranceTf);
        toloeranceTf.setBounds(380, 200, 110, 28);

        addBtn.setText("Calculate");
        add(addBtn);
        addBtn.setBounds(20, 370, 180, 50);

        anwserLbl.setText("jLabel1");
        add(anwserLbl);
        anwserLbl.setBounds(100, 260, 290, 100);

        ResetBtn.setText("Reset");
        add(ResetBtn);
        ResetBtn.setBounds(300, 370, 170, 50);

        headingLbl.setText("jLabel1");
        add(headingLbl);
        headingLbl.setBounds(10, 230, 130, 30);
        add(backgroundLbl);
        backgroundLbl.setBounds(0, 0, 500, 450);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(270, 100, 96, 27);
    }// </editor-fold>//GEN-END:initComponents

    private void firstcolorLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstcolorLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstcolorLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetBtn;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel anwserLbl;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JTextField firstcolorLbl;
    private javax.swing.JLabel frstnumLbl;
    private javax.swing.JLabel headingLbl;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel secondcolorLbl;
    private javax.swing.JTextField secondcolorTf;
    private javax.swing.JTextField thirdcolorLbl;
    private javax.swing.JLabel thridcolorLbl;
    private javax.swing.JLabel toloeranceLbl;
    private javax.swing.JTextField toloeranceTf;
    // End of variables declaration//GEN-END:variables
}
