/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analogsection;
import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author John
 */
public class WoodMainPanel extends javax.swing.JPanel {
    private Object button;

    /**
     * Creates new form WoodMainPanel
     */
    public WoodMainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        TitleLbl = new javax.swing.JLabel();
        InfoLbl = new javax.swing.JLabel();
        QuizLbl = new javax.swing.JLabel();
        WhatsLbl = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        WhatsBtn = new javax.swing.JButton();
        QuizBtn = new javax.swing.JButton();
        InfoBtn = new javax.swing.JButton();

        setLayout(null);

        TitleLbl.setBackground(new java.awt.Color(255, 255, 255));
        TitleLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        TitleLbl.setText("This is the Wood Sections main screen");
        add(TitleLbl);
        TitleLbl.setBounds(60, 20, 320, 30);

        InfoLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\rsz_1rsz_1imageedit_4_4600978165.png")); // NOI18N
        InfoLbl.setText("jLabel3");
        add(InfoLbl);
        InfoLbl.setBounds(70, 150, 140, 70);

        QuizLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\rsz_1rsz_1rsz_quiz.jpg")); // NOI18N
        QuizLbl.setText("jLabel4");
        add(QuizLbl);
        QuizLbl.setBounds(240, 140, 140, 60);

        WhatsLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\rsz_title859716636.png")); // NOI18N
        WhatsLbl.setText("jLabel6");
        add(WhatsLbl);
        WhatsLbl.setBounds(130, 230, 160, 70);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\John\\Desktop\\Wood-Background-Texture-452x336.jpg")); // NOI18N
        add(BackgroundLbl);
        BackgroundLbl.setBounds(0, -10, 450, 350);

        WhatsBtn.setBackground(new java.awt.Color(255, 255, 255));
        WhatsBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        WhatsBtn.setText("\"Whats It Made Of\"");
        WhatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhatsBtnActionPerformed(evt);
            }
        });
        add(WhatsBtn);
        WhatsBtn.setBounds(130, 230, 160, 70);

        QuizBtn.setBackground(new java.awt.Color(255, 255, 255));
        QuizBtn.setText("To image Quiz");
        QuizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizBtnActionPerformed(evt);
            }
        });
        add(QuizBtn);
        QuizBtn.setBounds(240, 140, 140, 60);

        InfoBtn.setBackground(new java.awt.Color(255, 255, 255));
        InfoBtn.setText("To Wood Info");
        InfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBtnActionPerformed(evt);
            }
        });
        add(InfoBtn);
        InfoBtn.setBounds(70, 150, 120, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void InfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBtnActionPerformed
           LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "WoodInfoScreen");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_InfoBtnActionPerformed

    private void QuizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizBtnActionPerformed
            LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "WoodQuizScreen");
        }
          
          


// TODO add your handling code here:
    }//GEN-LAST:event_QuizBtnActionPerformed

    private void WhatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhatsBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof java.awt.CardLayout) {
            java.awt.CardLayout cl = (java.awt.CardLayout)layout;
            cl.show(getParent(), "WoodWhatsScreen");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_WhatsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JButton InfoBtn;
    private javax.swing.JLabel InfoLbl;
    private javax.swing.JButton QuizBtn;
    private javax.swing.JLabel QuizLbl;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton WhatsBtn;
    private javax.swing.JLabel WhatsLbl;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables

   
}
